version: "3"
services:
  todoapp-db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_PASSWORD=BCNTntqY6@ja
    volumes:
      - data:/var/lib/postgresql/data

  todoapp:
    image: hsivov/todo-app
    environment:
      - TZ=Europe/Sofia
    ports:
      - "80:8080"
    depends_on:
      - todoapp-db
volumes:
  data:
