version: "3"
services:
  todoapp-db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - data:/var/lib/postgresql/data

  todoapp:
    image: hsivov/todo-app:v2.0
    environment:
      - TZ=Europe/Sofia
    ports:
      - "8080:8080"
    depends_on:
      - todoapp-db
volumes:
  data:
